[versions]
kotlin = "2.4.0"
idea-ext = "1.4.1"
commons-cli = "1.11.0"
jackson-databind = "3.2.0"
snakeyaml = "2.6"
javalin = "7.2.2"
jetty-client = "11.0.26"
junit-bom = "6.1.1"
leshan = "1.5.0"
logback = "1.5.37"
mockito = "5.23.0"
mockk = "1.14.11"
slf4j = "2.0.18"
spotless = "8.8.0"
problem4j-core = "1.4.3"
problem4j-jackson3 = "1.4.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }

# direct versions
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson-databind" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin", version.ref = "jackson-databind" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty-client" }
leshan-client-cf = { module = "org.eclipse.leshan:leshan-client-cf", version.ref = "leshan" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
problem4j-core = { module = "io.github.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson3 = { module = "io.github.problem4j:problem4j-jackson3", version.ref = "problem4j-jackson3" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
