[versions]
jackson-databind = "3.1.0"
jackson-dataformat-yaml = "3.1.0"
javalin = "7.1.0"
jetty-client = "11.0.26"
junit-bom = "6.0.3"
jaxws = "2.3.1"
leshan = "1.5.0"
logback = "1.5.32"
lombok = "1.18.42"
mockito = "5.23.0"
slf4j = "2.0.17"
spotless = "8.3.0"
problem4j-core = "1.4.3"
problem4j-jackson3 = "1.4.3"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }

# direct versions
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jackson-dataformat-yaml = { module = "tools.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson-dataformat-yaml" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty-client" }
jaxws-api = { module = "javax.xml.ws:jaxws-api", version.ref = "jaxws" }
leshan-client-cf = { module = "org.eclipse.leshan:leshan-client-cf", version.ref = "leshan" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
problem4j-core = { module = "io.github.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson3 = { module = "io.github.problem4j:problem4j-jackson3", version.ref = "problem4j-jackson3" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
